Vagrant.configure("2") do |config|
    config.vm.box = "generic/debian11"
    config.vm.synced_folder  ".", "/vagrant", disabled: false

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus   = 1
    end

#ЛОГИН ПАРОЛЬ ДЛЯ ВХОДА JENKINS admin admin 
    config.vm.define "jenkins", primary: true do |jenkins|
        jenkins.vm.network "private_network", ip: "192.168.56.3"
        jenkins.vm.provision "shell", inline: <<-SHELL
            
            apt-get install -y ansible
            sudo apt-get update 
            apt-get install -y sshpass

            sed -i "s/^PasswordAuthentication no\$/PasswordAuthentication yes/g" /etc/ssh/sshd_config
            service sshd restart
        SHELL
        jenkins.vm.hostname = "jenkins"
        jenkins.vm.provider("virtualbox") { |vb| vb.memory = 2048 }
        jenkins.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "playbook.yml"
            ansible.inventory_path = "inventory.ini"
        end
    end
end