Vagrant.configure("2") do |config|
    config.vm.box = "debian/buster64"
    config.vm.network "forwarded_port", guest: 80, host: 8080
  
    config.vm.synced_folder  ".", "/vagrant", disabled: false
  
    config.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "1/playbook.yaml"
    end
  end