Vagrant.configure("2") do |config|
    config.vm.box = "generic/centos8s"

    config.vm.synced_folder  ".", "/vagrant", disabled: false
  
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = 1
    end

    config.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbook.yaml"
    end
  end