Vagrant.configure("2") do |config|
    config.vm.box = "debian/buster64"

    config.vm.provider "virtualbox" do |vb|
        vb.name = "gitdemo.vagrant.vm"
        vb.memory = "512"
    end

    config.vm.network "forwarded_port", guest: 80, host: 8082
    config.vm.network "forwarded_port", guest: 80, host: 8083

    config.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y php

    SHELL

    config.vm.provision "file", source: "index.html", destination: "/var/www/html/index.html"
    config.vm.provision "file", source: "index.php", destination: "/var/www/html/index.php"
end