name: Build Push Docker image

on:
  push:
    #branches

  workflow_dispatch:

env:
  NAME_IMAGE: wcg
  VERSION_IMAGE: latest


jobs:
  buildandpush:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ACTION_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          file: 07-docker/Dockerfile.multi
          push: true
          tags: |
            ghcr.io/${{ steps.string.outputs.lowercase }}/${{ env.github.repository_owner }}/wcg:${{ github.sha }}
            ghcr.io/${{ steps.string.outputs.lowercase }}/${{ env.github.repository_owner }}/wcg:latest
