name: Build Push Docker image

on:
  push:
    #branches

  workflow_dispatch:

env:
  NAME_IMAGE: wcg
  VERSION_IMAGE: latest
  URL_DOCKERFILE: https://raw.githubusercontent.com/akirpaniou/devops-hometasks/master/07-docker/Dockerfile.multi

jobs:
  buildandpush:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - id: string
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository_owner }}
      
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ACTION_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.URL_DOCKERFILE }}
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ steps.string.outputs.lowercase }}/${{ env.NAME_IMAGE }}:${{ env.VERSION_IMAGE }}
            ghcr.io/${{ steps.string.outputs.lowercase }}/${{ env.NAME_IMAGE }}:${{ github.sha }}
