name: Build Push Docker image

on:
  push:
    #branches

  workflow_dispatch:

env:
  NAME_IMAGE: wcg
  VERSION_IMAGE: latest
  URL_DOCKERFILE: https://raw.githubusercontent.com/akirpaniou/devops-hometasks/master/07-docker/Dockerfile.multi


jobs:
  buildandpush:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.0.2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ACTION_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.URL_DOCKERFILE }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ env.NAME_IMAGE }}:${{ env.VERSION_IMAGE }}
            ghcr.io/${{ env.NAME_IMAGE }}:${{ github.sha }}
