name: Build Push Docker image

on:
  push:
    #branches

  workflow_dispatch:


jobs:
  buildandpush:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ACTION_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/wcg:latest -t ghcr.io/${{ github.repository_owner }}/wcg:${{ github.sha }} -f Dockerfile.multi .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/wcg:latest
          docker push ghcr.io/${{ github.repository_owner }}/wcg:${{ github.sha }}
